name: emkamed_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  lottie: ^2.7.0
  fl_chart: ^0.66.0
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  syncfusion_flutter_charts: ^23.1.42
  qr_code_scanner: ^1.0.1
  mqtt_client: ^9.7.2
  flutter_local_notifications: ^18.0.1
  flutter_background_service: ^5.1.0
  permission_handler: ^11.0.0
  flutter_background: ^1.3.0+1
  workmanager: ^0.5.2
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/logo-lottie.json
    - assets/icons/voltage.svg
    - assets/icons/temperature.svg
    - assets/icons/current.svg
    - assets/icons/power_battery.svg
    - assets/emka_logo.png
    - assets/connection.png
    - assets/register.png
    - assets/loader_2.json
    - assets/icons/dashboard.svg
    - assets/icons/analysis.svg
    - assets/icons/settings.svg
    - assets/link.png
    - assets/link2.png
    - assets/onboarding/easy_to_use.png
    - assets/onboarding/monitoring.png
    - assets/onboarding/alerting.png
